### ISSUE TITLE
Quantum Measurement main checklist

### ISSUE THREAD

**Issue by jbphet** [phetsims/quantum-measurement#1]
# Quantum Measurement main checklist

## Design

- [x] **Sim folder and design doc created** (Date: 5/2/2024)
  - [x] Create sim folder
    in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs
    account
  - [x] Place design doc in the sim folder
- [x] **Review user feedback** - [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=898967246)
- [x] **Learning goals and standards identified** (Date: //)
- [x] **Design concept complete**  (Date: //)
- [x] **Wireframes complete** (Date: //)
- [v] **Mockups complete** (Date: //)
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion**
- [x] **Interviews complete** (Date: //)
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [ ] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: //)
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [ ] **Prototype items**
  - [ ] Auxiliary screenshots (at least 1 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL) as appropriate
  - [ ] Email/Twitter announcement language
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Send Simulation Notification from the Admin page (to alert translators)
- [ ] **Pre-publication items**
  - [x] Auxiliary screenshots (up to 3 additional)
  - [x] Screen-specific screenshots for metadata service (
    see [naming convention](https://github.com/phetsims/website/issues/1322#issuecomment-1010320827))
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Accessibility features
  - [ ] [Draft the Email announcement language](https://github.com/phetsims/tasks/issues/new?assignees=&labels=tasks%3Aemail&projects=&template=sim-announcement-email.md&title=Sim+Announcement+Email)
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each
    screen created and uploaded to Drive
  - [ ] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429)
    for each screen (description, vocab words, questions for before/after sim use)
- [x] **Make sim visible on website**
  - [ ] Clear "Metadata caches" on
    the [Basic Administration Caches](https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminCachesPage)
    page
- [ ] **Post-publication items**
  - [ ] Share new features, design challenges, and treats with group!
  - [ ] Email announcement
  - [ ] Deliver
    to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Create "sim primer" issue
  - [ ] Hold postmortem if applicable (Date: //)
  - [ ] Send Simulation Notification from the Admin page (to alert translators)

## Inclusive Features

- [x] Alternative Input (Started: ) (Completed: )
  - [x] Separate ScreenView controls into play area PDOM vs control area PDOM
  - [x] Create screen-specific Keyboard Shortcuts Dialogs.
    - [x] Ensure all sim-specific actions come before "Basic Actions".
    - [x] Adjust the dialogs default headings and instructions to suit the sim where needed. 
  - [x] Interactive Highlights
- [ ] Sound & Sonification (Completed: )
  - [ ] Sound design requirements determined: date: //
  - [ ] Sound design complete: date: //
  - [x] UI Sounds implemented: date: //
  - [ ] All sounds implemented: date: //
- [ ] Interactive Description - (link to description design & implementation checklist)
  - [ ] Description design complete (Started: ) (Completed: )
  - [ ] Development complete (Started: ) (Completed: )
  - [ ] Mobile description included
- [ ] Voicing - (include links to relevant voicing design document)

## Implementation

- [x] **Repository created** by
  following [new-repo-checklist.md](https://github.com/phetsims/phet-info/blob/main/checklists/new-repo-checklist.md) (
  Date: 5/16/2024)
- [x] **Development started** (Date: 5/16/2024)
- [x] **Sim is "feature complete"** (Date: //)
- [x] **QA team "first look"** (Date: //)
- [x] Interviews may happen around here (see above)
- [x] **Sim team sign-off** (Date: //)
- [x] **Code review completed** (Date: //)
- [x] **Sim dev test completed** (Date: //)
- [x] **Sim RC tests completed** (Date: //)
- [ ] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md#screenshots))
  - [x] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks -
    see [conventions](https://github.com/phetsims/joist/blob/main/js/CreditsNode.js))
  - [ ] Add CT tests for public query parameters that need testing. See examples
    in [listContinuousTests.js](https://github.com/phetsims/perennial/blob/main/js/listContinuousTests.js)
- [x] **Published** (Date: //)

## QA

- [x] **Dev testing started** (Date: //)
- [x] **Dev testing completed** (Date: //)
- [x] **First RC published** (Date: //)
  - [ ] Test matrices put
    in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: //)

**Comment by jbphet** [comment]
I've been asked to focus on getting "Mean: Share and Balance" out the door, and this sim - "Quantum Measurement" - is now on the back burner for a while. I'm going to defer this issue until this sim becomes a priority again.

**Comment by jbphet** [comment]
The sim is now published, so I'm going to close this issue.  We didn't do a great job up keeping this updated throughout the development process, so there are a number of items that never got checked off and/or dates added.  Nonetheless, I feel like this issue served its purpose.

**Comment by jbphet** [comment]
Actually, I'm going to reopen and follow up on a few things, like having a post mortem and doing the "sim primer", whatever that is.

**Comment by jbphet** [comment]
We discussed at the last iteration planning meeting whether we felt we needed to do a post mortem for this sim and the consensus was that it wasn't necessary given the other priorities that we all have.  I think it is now safe to close this.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by jbphet** [comment]
I've addressed the TODO items that caused this to be automatically reopened.  I have to say, this is  a pretty good thing we have in place, since these things really should have been addressed and I'd just missed them, and it makes the code cleaner.  Closing (again).
